/** @generated by tools/convert-button-sfx-to-opus.mjs — do not edit by hand */
const BUTTON_SFX_DIR = '/audio/buttons';

export const BUTTON_SFX_TARGET_URLS = [
  `${BUTTON_SFX_DIR}/target.ogg`,
  `${BUTTON_SFX_DIR}/target2.ogg`,
] as const;

export const BUTTON_SFX_PRESS_URLS = [
  `${BUTTON_SFX_DIR}/press1.ogg`,
  `${BUTTON_SFX_DIR}/press2.ogg`,
] as const;

export const BUTTON_SFX_PLAY_URL = `${BUTTON_SFX_DIR}/play.ogg`;

export const BUTTON_SFX_ALL_URLS: readonly string[] = [
  ...BUTTON_SFX_TARGET_URLS,
  ...BUTTON_SFX_PRESS_URLS,
  BUTTON_SFX_PLAY_URL,
];
