/** @generated by tools/convert-menu-noise-to-webp.mjs — do not edit by hand */
const MENU_NOISE_DIR = '/assets/menu noise';

export const MENU_NOISE_WEBP_FILES: readonly string[] = [
  "1 (2).webp",
  "2 (2).webp",
  "3 (2).webp",
  "4.webp",
  "5.webp",
  "6.webp",
];

export function menuNoiseWebpUrl(fileName: string): string {
  return `${MENU_NOISE_DIR}/${encodeURI(fileName)}`;
}

export const MENU_NOISE_WEBP_URLS: readonly string[] = MENU_NOISE_WEBP_FILES.map(
  menuNoiseWebpUrl,
);

/** Desktop / mouse-first viewport — hide menu noise on phones and tablets. */
export function isDesktopMenuNoiseViewport(): boolean {
  return window.matchMedia('(hover: hover) and (pointer: fine)').matches;
}

export function pickRandomMenuNoiseWebpUrl(): string {
  const urls = MENU_NOISE_WEBP_URLS;
  return urls[Math.floor(Math.random() * urls.length)] ?? urls[0]!;
}
